### ISSUE TITLE
missing header detection of rtcp

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [Upipe/upipe#126]
I have an error during build:
upipe_rtcp.c:45:33: fatal error: bitstream/ietf/rtcp.h: No such file or directory

I solved using flag on configure: --disable-rtcp
But it can be fine to check header presence during configure.

**Comment by kierank** [comment]
It's in latest bitstream.

**Comment by nto** [comment]
Upipe git master always requires bitstream's git master. For official releases, Upipe now checks bitstream's version using it's pkg-config file.
